// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/manga": {
            "get": {
                "description": "Lists all manga in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "summary": "List all manga",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Manga"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a manga in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "summary": "Create a manga",
                "parameters": [
                    {
                        "description": "Manga",
                        "name": "manga",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Manga"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Manga"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "simple health check handler that returns 200 OK and is used for Kubernetes liveness probes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Manga": {
            "type": "object",
            "required": [
                "author",
                "magazine",
                "publisher",
                "title"
            ],
            "properties": {
                "author": {
                    "description": "Author is the author of the manga",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the manga ID used to make it unique in the database",
                    "type": "string"
                },
                "magazine": {
                    "description": "Magazine is the magazine the manga was published in",
                    "type": "string"
                },
                "publisher": {
                    "description": "Publisher is the publisher of the manga",
                    "type": "string"
                },
                "title": {
                    "description": "Title is the title of the manga",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Chi No Wadachi API",
	Description:      "This is a simple API that is used to demonstrate how to use Chi as a web framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
